### ISSUE TITLE
makePictureTree does not support CNAME

### ISSUE THREAD

**Issue by davidlima88** [filestack/adaptive#15]
https://github.com/filestack/adaptive/blob/18602bbaf8c5c4de6e57d3525c92a49c1d5a598d/src/tree.ts#L288

I couldn't find a way in the documentation to pass a CNAME value to replace the default URL "https://cdn.filestackcontent.com"

**Comment by AndrzejSala** [comment]
Hi,
I just released a new version in which PictureOptions can get 'cname'.
https://github.com/filestack/adaptive#custom-cname

**Comment by davidlima88** [comment]
Thanks, Andrzej. It works perfectly.
